### ISSUE TITLE
Debug mode is not accessible for remote debugging

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-cli#106]
nodemon --inspect defaults to 127.0.0.1:9229 for debugging. Since I use docker containers in my development workflow, my debugger cannot connect (different virtual network interface).

It should be a fairly quick/non-breaking fix:

`- nodemon --inspect`
`+ nodemon --inspect=0.0.0.0:9229`

https://github.com/adonisjs/adonis-cli/blob/develop/src/Commands/Serve/index.js#L181

What do you think?

**Comment by RomainLanz** [comment]
Hey @nrempel! 👋 

Could you create a PR for this fix?

**Comment by nrempel** [comment]
Yes, absolutely!

I'll try and do this soon.

**Comment by thetutlage** [comment]
I am not sure if Chrome is always going to stick to `9229` port or not and also if they use logic to switch between `9229` or any other port. So I don't want to hardcode it inside the code.

This PR https://github.com/adonisjs/adonis-cli/pull/88 allow passing a custom port, in your case, you can pass host and port both.

```js
adonis serve --debug=0.0.0.0:9229
```
