### ISSUE TITLE
[bug] --no-ansi option returns nothing

### ISSUE THREAD

**Issue by sundowndev** [adonisjs/adonis-cli#118]
`--no-ansi` option returns nothing.

## Package version
4.0.10

## Node.js and npm version
node v8.15.0
npm 6.5.0

## Sample Code (to reproduce the issue)
`$ adonis --no-ansi`

**Comment by RomainLanz** [comment]
Hey @sundowndev! 👋 

This system is going to change in the next version.

**Comment by thetutlage** [comment]
@RomainLanz Why you think it's a bug. Works fine for me

```sh
adonis --help --no-ansi
```
