### ISSUE TITLE
Adonis CLI not work

### ISSUE THREAD

**Issue by emjeard** [adonisjs/adonis-cli#120]
Hi, after install adonis cli via npm and try on command prompt always show like this.

'adonis' is not recognized as an internal or external command,
operable program or batch file.

How to solve this?
thanks before

**Comment by RomainLanz** [comment]
Hey @emjeard! 👋 

Ensure to have the installation folder of your global NPM module in your `PATH`.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by agwenchez** [comment]
After npm install -g @adonisjs/cli, i have tried to add a new path in system variables, pointing to the installation folder of the global NPM package but i still get the same problem, Adonis not recognized as an internal or external command, operable program or batch file.
Kindly assist .
Thanks

**Comment by Karlheinzniebuhr** [comment]
Same issue on windows 10 with npm version 6.9.0

**Comment by yusren** [comment]
I also faced this problem.
Step one 
Run `npm i -g @adonisjs/cli` with Non Administrator's access CLI.
then make sure the lines below are in the PATH list, both on user variables and system variables. Then restart the CLI. Give it try.
`C:\Users\<username>\AppData\Roaming\npm`

**Comment by mq003at** [comment]
It doesn't work for me. I tried to install but there is no adonis cli directory  `C:\Users\<username>\AppData\Roaming\npm\node_modules`. I can't even find the `.cmd` files to put it in the `PATH`. 
I have this issue with ionic, but quickly solve it by putting these `.cmd` files in system variables, but Adonis/cli github doesn't provide a `.cmd` file

**Comment by minhtranin** [comment]
i even faced with issue, can anyone help me ? kindly assist

**Comment by Trapintrovert** [comment]
> I also faced this problem.
> Step one
> Run `npm i -g @adonisjs/cli` with Non Administrator's access CLI.
> then make sure the lines below are in the PATH list, both on user variables and system variables. Then restart the CLI. Give it try.
> `C:\Users\<username>\AppData\Roaming\npm`

Thank you. You saved a life!
