### ISSUE TITLE
Please add a .gitignore file in database folder for sqlite

### ISSUE THREAD

**Issue by memochou1993** [adonisjs/adonis-cli#122]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Lots of raised issues are directly not bugs but instead are design decisions taken by us.
- Make use of our [forum](https://forum.adonisjs.com/), or [discord server](https://discord.me/adonisjs), if you are not sure that you are reporting a bug.
- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Package version

5.0.8

## Node.js and npm version

v11.3.0

6.5.0

## Sample Code (to reproduce the issue)

Please add a .gitignore file in database folder for sqlite:

 *.sqlite

**Comment by RomainLanz** [comment]
Hey @memochou1993! 👋 

Nothing keeps you from adding it yourself.
