### ISSUE TITLE
Version 4.1 documented but not published

### ISSUE THREAD

**Issue by kattatzu** [adonisjs/adonis-cli#123]
Hello, first of all congratulate them for this excellent framework, it helps a lot to launch applications quickly.

My observation is that reading the documentation appear features that have not yet been published, specifically the option to generate validators in the console (adonis make: validator StoreUser) which corresponds to version 4.1, however the latest published version is 4.0.

Do you have an estimated date of publication of this version?

**Comment by RomainLanz** [comment]
Hey @kattatzu! 👋 

Sorry for the very late reply!
I didn't get your issue, the documentation for version 4.1 are published on the website.

**Comment by IlyaSovenko** [comment]
@RomainLanz But how can we use features from 4.1 version?) Cli is just 4.0.12 version, where we don't have make:test make:validator commands, and so on. Do you have date of release cli for current version of documentation? Thanks a lot

**Comment by RomainLanz** [comment]
Hey @IlyaSovenko! 👋 

The CLI has its own version.
Feel free to [follow the documentation](https://adonisjs.com/docs/4.1/testing#_setup) to install testing packages.
