### ISSUE TITLE
fs.pathExists is not a function

### ISSUE THREAD

**Issue by brenoos** [adonisjs/adonis-cli#132]
Hello. 

I'm trying to install the package, and I'm getting the error 

> fs.pathExists is not a function

![Captura de tela de 2019-04-06 16-31-36](https://user-images.githubusercontent.com/16320379/55674330-b875c300-5889-11e9-9c6a-65d83251cde6.png)

**Comment by brenoos** [comment]
I'm on Ubuntu 18.04.2 LTS

**Comment by RomainLanz** [comment]
You may have something wrong with your Node.js setup to make this happen.

I've tried on macOS, Windows & Linux (Ubuntu 18.04.2 LTS) but I wasn't able to reproduce the issue.
Therefore, I'm closing this issue since it's clearly not related to Adonis nor Adonis CLI.

**Comment by italomlp** [comment]
@RomainLanz I got this too. I was trying to install `@adonisjs/mail` and face this message:
```
[1/1] 📦  Dependencies installed [@adonisjs/mail]
ERROR  fs.pathExists is not a function
```
Node version: 8.16.0 and 10.16.0
Yarn version: 1.15.2
NPM version: 6.9.0

I tried with both yarn and npm, but nothing. I think that it's from here:
https://github.com/adonisjs/adonis-cli/blob/5d519478dd22df241bab214cad59d8bc5f940280/src/Services/run-instructions.js#L31
