### ISSUE TITLE
Ability to log commands and get exit code

### ISSUE THREAD

**Issue by Melchyore** [adonisjs/adonis-cli#133]
## Why this feature is required (specific use-cases will be appreciated)?
Since we can't monkey patch globally installed package and adonis-cli is one of them, we can't add more features from 3rd party package.

## Have you tried any other work arounds?
Yes, I tried like this in index.js (lines: 40-42) :
```js
#!/usr/bin/env node
'use strict'

/*
 * adonis-cli
 *
 * (c) Harminder Virk <virk@adonisjs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/

const path = require('path')
const debug = require('debug')('adonis:cli')

const Commands = require('./src/Commands')
const commandNames = []
const needProviders = ['repl', 'route:list', 'run:instructions']

const ace = require('./lib/ace')

// register internal commands
Object.keys(Commands).forEach((name) => {
  commandNames.push(name)
  ace.addCommand(Commands[name])
})

// require user project .ace file
try {
  const command = process.argv[2]
  if (commandNames.indexOf(command) > -1 && needProviders.indexOf(command) <= -1) {
    debug('loading ace from cli')
    ace.wireUpWithCommander()
    ace.invoke(require('./package'))
  } else {
    debug('loading ace from project')
    require(path.join(process.cwd(), 'ace'))
  }

  process.on('exit', code => {
    console.log([ ...process.argv, code ])
  })
} catch (error) {
  if (error.code !== 'ENOENT' && error.code !== 'MODULE_NOT_FOUND') {
    throw error
  }

  debug('loading ace as fallback from cli')
  ace.wireUpWithCommander()
  ace.invoke(require('./package'))
}
```
But it doesn't work as expected, if a command uses multiple choices, selected one will not be caught. We can't even send data to the parent process (AKA adonis application) as it uses spawn instead of fork I guess...

## Are you willing to work on it with little guidance?
Maybe.

**Comment by RomainLanz** [comment]
Hey @Melchyore! 👋 

I'm sorry, but I didn't get what you are trying to do.
Do you want to add commands from a third party package?

**Comment by Melchyore** [comment]
Hello @RomainLanz !
No that's not what I'm looking for. What I want is to do something like this in my application
```javascript
Event.on('command:make:controller', cb)
```
`cb` is the callback function that will return command name, arguments, options (flags), and exit code.
For example, if I run the following command `adonis make:controller Foo` the callback will return this object :
```json
{
  "exit_code": 0, // 1 if there was an error
  "name": "make:controller",
  "args": {
    "name": "Foo"
  },
  "options": {
    "type": "http | ws", // Depending on user selection...
    "resource": false
  }
}
```

Excuse me if it wasn't clear.

As I said it's just an example but that would be so useful.

**Comment by thetutlage** [comment]
What’s the use case for this?

**Comment by Melchyore** [comment]
@thetutlage it will help me for this https://github.com/adonisjs/rfcs/issues/16

**Comment by thetutlage** [comment]
@Melchyore We first need to finalize the approach for tracking all that information and then move to individual repos and enable required API's.

Closing this for now
