### ISSUE TITLE
Allow watch override ignore directories

### ISSUE THREAD

**Issue by McSneaky** [adonisjs/adonis-cli#134]
## Why this feature is required (specific use-cases will be appreciated)?
Currently there is no way for Adonis CLI to watch for `tmp`, `resources` and `public` folders. Since they are hard-coded into ignore list.

It would be nice, if you can add them with `--watch` or files in them with `--ext`.
Since in underlying nodemon ignore list has power over watch list files and folders. [nodemon faq](https://github.com/remy/nodemon/blob/master/faq.md#what-has-precedence-ignore-or-watch)

It would be especially good for .edge files development in resource files

## Have you tried any other work arounds?
Tried `adonis serve -w /resources/*` which did not work.
Also `adonis serve --dev --ext edge` does not work

There is possibility to add custom script into package.json but it is not as clean as using Adonis CLI. It would require installing nodemon (or anything similar) and nodemon.json config file

## Are you willing to work on it with little guidance?
Yes. 
Already fixed it on my [fork](https://github.com/McSneaky/adonis-cli/blob/develop/src/Commands/Serve/index.js#L160). Not sure if it is acceptable tho

**Comment by thetutlage** [comment]
The `edge` files doesn't need the server to be restarted, since they are compiled on every Http request (when CACHE_VIEWS=false). 

Also, the `resources` folder is mainly in place for frontend related code, is their any specific reason you want to start AdonisJs server when your frontend code changes.

It will be nice to have some real world examples

**Comment by McSneaky** [comment]
Aaaah.. Stupid me :smile: 

Didn't think about views cache.. Disabling it and all works as intended

I can't figure out currently any more use-cases for it currently. If someone has any then it might come handy.

From my point of view it can be closed :slightly_smiling_face:
