### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by yasinakcadev** [adonisjs/adonis-cli#138]
When I type the adonis command (e.g adonis make:controller Index) the command line says 
I'm using windows 10. Can anyone please help me?
adonis : The term 'adonis' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
 if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ adonis make:controller
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (adonis:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by RomainLanz** [comment]
Hey @yasinakca! 👋 

You need to add `npm` or `yarn` global installation path to your PATH variable.

**Comment by yasinakcadev** [comment]
Hi @RomainLanz 
I added the path already but the issue is still continuing.

Here is a snapshot: 
![Screenshot_1](https://user-images.githubusercontent.com/15368330/60171355-28557300-9813-11e9-975c-16fa66b4f103.png)

**Comment by RomainLanz** [comment]
This is not the path your should add.

You should add **npm** global bin path, not Adonis CLI path.
```
%USERPROFILE%\AppData\Roaming\npm\node_modules\.bin
```

**Comment by yasinakcadev** [comment]
It's working fine when I use your advice. Thank you very much.
