### ISSUE TITLE
Adonis Cannot find module

### ISSUE THREAD

**Issue by nklowns** [adonisjs/adonis-cli#151]
## Prerequisites
Follow the instructions here https://adonisjs.com/docs/4.1/installation
```
PS C:\Deployment\Kuork\api.kuork> npm i -g @adonisjs/cli

npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
C:\Oongbsd\Scoop\apps\nvm\current\nodejs\nodejs\adonis -> C:\Oongbsd\Scoop\apps\nvm\current\nodejs\nodejs\node_modules\@adonisjs\cli\index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@adonisjs\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @adonisjs/cli@4.0.12
```

then run adonis on powershell
```
PS C:\Deployment\Kuork\api.kuork> adonis
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'promise-reduce'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Oongbsd\Scoop\persist\nvm\nodejs\v10.16.0\node_modules\@adonisjs\cli\node_modules\enquirer\index.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Package version
@adonisjs/cli@4.0.12

## Node.js and npm version
Node.js v10.16.0
Npm v6.9.0

**Comment by agtabesh** [comment]
I have the same problem. A fresh install tell me there is two vulnerabilities and ask me to run `npm audit fix` to resolve them. `npm audit` returns this:
```bash
                       === npm audit security report ===                        
                                                                                
# Run  npm install @adonisjs/ace@6.1.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ set-value                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @adonisjs/ace                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @adonisjs/ace > enquirer > prompt-question > prompt-choices  │
│               │ > set-value                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1012                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ set-value                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @adonisjs/ace                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @adonisjs/ace > enquirer > set-value                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1012                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

```


But right after running `npm audit fix`, any adonis command throw an error like this:

```bash
/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/Base/index.js:17
class BaseCommand extends ace.Command {
                              ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/Base/index.js:17:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@adonisjs/cli/src/Commands/New/index.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

## Package version
@adonisjs/cli@4.0.12

## Node.js and npm version
Node.js v10.15.1
Npm v6.10.1

**Comment by mq003at** [comment]
I also have an error like that

`internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'C:\Users\mq003\AppData\Roaming\@adonisjs\cli\index.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}`

That module exists in my pc. I have imported it back to the directory it was asked for. However, things still don't work.
![ảnh](https://i.stack.imgur.com/aoBeE.png)

Edit: eventually I found out the solution so I put stackoverflow post here.
[Stackoverflow](https://stackoverflow.com/questions/57287382/adonis-is-not-recognized-as-an-internal-or-external-command-problem-even-tho?noredirect=1#comment101069598_57287382)

**Comment by Secular12** [comment]
@agtabesh I ran into the same problem, have you found a fix or a way to revert back? Now I cannot use Adonis at all

**Comment by thetutlage** [comment]
Upgrading to a major release of any package and still expect it to work is a false assumption.

Simply use the version `5.0.8` of ace and everything will be fine

**Comment by mayankgandhi** [comment]
Having the same problem for one of my applications. Are you guys on MacOS Catalina Public Beta by any chance?

**Comment by thetutlage** [comment]
@mayankgandhi Did you even read the last comment? You should not upgrade the version of `@adonisjs/ace` in your app

**Comment by nklowns** [comment]
> Upgrading to a major release of any package and still expect it to work is a false assumption.
> 
> Simply use the version `5.0.8` of ace and everything will be fine

Solved by @thetutlage

**Comment by CristianEchartea** [comment]
Me sucedio el mismo error y era por que habia instalado una version mas reciente, me di cuanta cuando entre a mi package.json especialmente viendo las siguientes lineas dentro de las dependecias:
"@adonisjs/ace": "^6.8.4",
"@adonisjs/lucid": "^7.6.3",

Yo lo resolvi cambiando las versiones por las siguientes: 

"@adonisjs/ace": "^5.0.8"
 "@adonisjs/lucid": "^6.1.3",

Guarde los cambios y ejecute el siguiente comando en consola:

npm install --production

**Comment by luccabassoli** [comment]
Hello, I need to make cron (task) run my website invoices, but it doesn't work because it can't find the module that would be my file, does anyone know how we can fix it?
