### ISSUE TITLE
Adonis command doesn't recognize my project in Staging environment

### ISSUE THREAD

**Issue by leandrofinger** [adonisjs/adonis-cli#164]
I'm using Capistrano to do deploys in Staging and when I go to the app directory (inside current release) I run the command `adonis repl` and nothing happen. When I run just `adonis` to see the available commands, it seems to not recognize the project as an Adonis project.
```bash
$ adonis
Usage:  [options] [command]

Options:
  -h, --help            output usage information

Commands:
  new [options] <name>  Scaffold a new AdonisJs application with the name provided.
  Extras:

    [command] --help output command detail info
```

This is my directory tree:
```
|-- Capfile
|-- Dockerfile
|-- README.md
|-- REVISION
|-- ace
|-- app
|-- bitbucket-pipelines.yml
|-- config
|-- database
|-- docker-compose.yml
|-- log
|-- node_modules
|-- package-lock.json
|-- package.json
|-- server.js
|-- start
|-- startup.sh
|-- test
|-- vowfile.js
`-- yarn.lock
```

**Comment by RomainLanz** [comment]
Hey @leandrofinger! 👋 

In which directory do you execute the `adonis` command?

**Comment by leandrofinger** [comment]
Hi Romain!

As Capistrano deploys the application into a current directory, I ran the
command inside of it.

**Comment by RomainLanz** [comment]
Hey @leandrofinger! 👋 

Sorry for the delay.
Have you managed to fix the issue?

What happen when you run `node ace` in this repository?

**Comment by RomainLanz** [comment]
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.
