### ISSUE TITLE
run ace when on project directory

### ISSUE THREAD

**Issue by mastito03** [adonisjs/adonis-cli#17]
it just idea.
why not make this command run as alias for ace when on project directory. like this we don't need to use two command for make new project and managing project. and it make this command use more often. but it just alias so use ace command is no problem.

**Comment by RomainLanz** [comment]
Hey @mastito03 !

We already discuss of this idea with @thetutlage but it seems that it could confuse people. We will reconsider this demand and see what we can do. `adonis-cli` is currently rewritten in top of `adonis-ace`.

**Comment by thetutlage** [comment]
Closing since not actionable
