### ISSUE TITLE
Could not install Adonis using NPM

### ISSUE THREAD

**Issue by masonchoo10** [adonisjs/adonis-cli#174]
Recentltly when I run the command  `npm i --global @adonisjs/cli` , I encountered the following errors:

```
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
C:\Users\kc.choo\AppData\Roaming\npm\adonis -> C:\Users\kc.choo\AppData\Roaming\npm\node_modules\@adonisjs\cli\index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@adonisjs\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @adonisjs/cli@4.0.12
updated 1 package in 35.036s
```

I checked no node_modules are being installed. Can you advise what's going on? Thanks in advance

My Node Version: 12.13.0
My NPM Version: 6.13.1

**Comment by RomainLanz** [comment]
Hey @chookarchun20! 👋 

There's nothing wrong, NPM warn you about few things, but nothing breaks and as the last line said, it has been installed.

**Comment by evgenx** [comment]
After install adonis cli I try:
`adonis new appName`
but:
`adonis not internal or external command`
How set manual $PATH ?

**Comment by masonchoo10** [comment]
@evgenx I faced the same issue before. But  try updating Node to version 13 and it seems the issue is gone. Give it a try too.

**Comment by evgenx** [comment]
@chookarchun20 nothing changed. 
```
c:\>npm -v 
6.13.1               
c:\>node -v
v13.2.0           
```

**Comment by RomainLanz** [comment]
Feel free to follow this tutorial to know how to setup your PATH variable on Windows: https://www.computerhope.com/issues/ch000549.htm

**Comment by afshinrahmati** [comment]
Do you find it ??? please say to me
