### ISSUE TITLE
Cannot read property 'major' of null

### ISSUE THREAD

**Issue by odansantos** [adonisjs/adonis-cli#175]
## Package version
4.0.12

## Node.js and npm version
Nodejs: 12.13.1
Npm: 6.12.1
Ubuntu: 19.10

## Sample Code (to reproduce the issue)
![](https://i.imgur.com/plDjnbg.png)

**Comment by odansantos** [comment]
I had installed node js via snap. When installing without it, worked normally

**Comment by mohssineAboutaj** [comment]
Any solution ?
I cant use nodeJs from **apt** because it's install only v8, so i'm using nodeJs from **snap**

### Update:
I use this solution to get [nodeJs v12](https://websiteforstudents.com/how-to-install-node-js-10-11-12-on-ubuntu-16-04-18-04-via-apt-and-snap/)
