### ISSUE TITLE
deprecated warnings

### ISSUE THREAD

**Issue by bingalls** [adonisjs/adonis-cli#177]
## Package version
4.0.12

## Node.js and npm version
node 13.7.0
npm 6.13.6

## Sample Code (to reproduce the issue)
npm i -g @adonisjs/cli

Yields these warnings. Critical bug looks important
```
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
```

**Comment by RomainLanz** [comment]
Hey @bingalls! 👋 

This is not an issue at all.
Closing.
