### ISSUE TITLE
-V flag should be -v

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-cli#25]
````
C:\Users\jk23\dev\my_projects
λ adonis -v

  error: unknown option `-v'


C:\Users\jk23\dev\my_projects
λ adonis -V
2.1.8
```

**Comment by thetutlage** [comment]
Yup will get it fixed. Thanks for reporting

**Comment by thetutlage** [comment]
Just realized it is from commander instead of `ace`. https://www.npmjs.com/package/commander#automated---help.

Closing since Adonis makes use of `commander`
