### ISSUE TITLE
adonis new --local

### ISSUE THREAD

**Issue by ajoslin103** [adonisjs/adonis-cli#38]
interesting reading lately recommending NOT installing packages globally, thereby ensuring that older codebases stay functional as they were built.

this means that to start a new adonis project I have to create a throw-away wrapper

```
mkdir yardstick_wrapper && cd $_
yarn init
yarn add --dev adonis-cli

adonis new yardstick --yarn
cd yardstick
yarn add --dev adonis-cli

cd ../..
mv yardstick_wrapper/yardstick .
rm -rf yardstick_wrapper
```

perhaps you could add a --local flag (or --here) to not create and enter the application directory?

**Comment by RomainLanz** [comment]
Hey @ajoslin103 👋 

> interesting reading lately

May you give us a link? 😄

**Comment by ajoslin103** [comment]
Originally I had watched a video which led me to a few articles -- I can't remember the video or articles...  But I did find a couple with G's help

https://www.smashingmagazine.com/2016/01/issue-with-global-node-npm-packages/

https://www.sitepoint.com/solve-global-npm-module-dependency-problem/

**Comment by RomainLanz** [comment]
I think you misunderstood the meaning of those articles.

`adonis-cli` is a CLI to help you quickly get ready to develop and is not required when you use Adonis.
You can clone the app repository and start using Adonis without even hearing about `adonis-cli`.

**Comment by ajoslin103** [comment]
I have become a huge fan of tooling over the last 5 years, and the tools are continually evolving.  

And I have experienced the issue of going back to a project after more than a year and the global installs of the tooling had been updated and it took many hours before I could build again

While this may not be a perfect case of the problem, the underlying issue does exist.  Breaking changes are part of our lives.  We can't always be backwards compatible if we are always moving our knowledge, understanding, and skills forward.

A global install of your cli may gracefully handle Adonis4 & Adonis3 projects without issue, but what about Adonis5?

What happens when I go back to some old Adonis3 code next year to add one small change, will I have to upgrade the whole project to Adonis4 in order to use the cli?

What if the command 'ace' is also used by someone else for something else?  When I was using Atom they had a terminal command: ace, for installing extensions.  Are these the same thing?  How does it know to do Atom work vs Adonis work?  And what about the ace editor, what if it has a command line tool named ace, as vsCode has taken the cmd line 'code'.

I know, based on this reasoning I should only install Node itself locally to a project...

Anyway, and as always, thanks for your time and work - it makes my life better !

**Comment by RomainLanz** [comment]
> What happens when I go back to some old Adonis3 code next year to add one small change, will I have to upgrade the whole project to Adonis4 in order to use the cli?

This CLI is only used once and only useful to create new project. If you are going back to an Adonis application you'll not need to use the CLI again.

The CLI that you will use is `ace`, and this one is inside your `package.json`.

**Comment by ajoslin103** [comment]
Ah, I had confused the cli with the ace.

And so, as usual, you are many steps ahead of me :) and already putting the ace command into the project, so it stays with the code.

How will I tell the cli if I want an Adonis3 or Adonis4 project?

**Comment by RomainLanz** [comment]
Which CLI? 😄 

I hope you'll always start a new project with the latest version, but you can define a `blueprint` inside `adonis-cli` if you want to target another repository (like Adonis 3.0 one).

Since `ace` is inside your local dependencies by default, you don't need to target a version when you use it.

**Comment by ajoslin103** [comment]
😄  indeed!  I don't expect to ever want to go back to Adonis3 once Adonis4 is released!!  
  -- but it's good to know that there is a way (even if there isn't a why)
