### ISSUE TITLE
Adonis-Cli Requires NPM Even When --yarn Flag Is On

### ISSUE THREAD

**Issue by abrahamy** [adonisjs/adonis-cli#39]
I use yarn exclusively for managing dependencies and for this reason I do not have npm installed. On Arch Linux nodejs, npm and yarn are separate packages so one can install only nodejs and yarn without npm. This is my current setup. However, after installing adonis-cli with `yarn global add adonis-cli` and attempting to create a project with `adonis new yardstick --yarn` I get the error in the attached image.

It appears adonis-cli is not honoring the `--yarn` flag. Should this be the expected behavior?
![deepinscreenshot20170527172701](https://cloud.githubusercontent.com/assets/8211487/26522877/08c8917e-4302-11e7-8eaf-0277139ce1f0.png)

**Comment by mrshll** [comment]
I find this to still be the case in v4.0.12

```
 !  marsh@marshbox  ~/workspace  adonis new yardstick --yarn
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___ 
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

⠋ [1/6] 🔬  Verifying requirements [node & npm]
   ERROR  Command failed: npm -v
/bin/sh: 1: npm: not found
```
