### ISSUE TITLE
Getting error after latest update.

### ISSUE THREAD

**Issue by Naoray** [adonisjs/adonis-cli#47]
I am getting the following error when trying to run `adonis` in command line:

```
/usr/bin/env: ‘node --harmony-async-await’: No such file or directory
```

Quick google found [this](https://github.com/SpencerCDixon/redux-cli/issues/42#issuecomment-192751444)

Using Ubuntu 16.04
Node: v8.2.1

**Comment by RomainLanz** [comment]
Hey @Naoray 👋 

Which version of the `adonis-cli` are you using?

**Comment by Naoray** [comment]
the latest: v3.0.2

**Comment by Naoray** [comment]
I updated to v3.0.2 but now I get an error in [new Command](https://github.com/adonisjs/adonis-cli/blob/develop/src/Commands/New/index.js#L114)

EDIT: just saw I was using node v6.11.0 switched to v8.2.1 and it works now
