### ISSUE TITLE
Command serve in dev mode add skip watch on exclude files

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/adonis-cli#49]
I write code in PhpStorm. IDE created dir `.idea`. In watch mode this dir is system and it is should not be watched.

Sample output log:

```
$ adonis serve --dev

 Started server in dev mode 

2017-08-11T12:19:12.424Z - info: serving app on http://127.0.0.1:3333
add  .idea/workspace.xml
2017-08-11T12:19:52.460Z - info: serving app on http://127.0.0.1:3333

```

**Comment by thetutlage** [comment]
Cool, I will add it to the list + will allow users to pass a custom set of directories to ignore

**Comment by ntvsx193** [comment]
Thanks!

**Comment by thetutlage** [comment]
Fixed and allowed custom `watch` dirs too https://github.com/adonisjs/adonis-cli/commit/23f17987c0a558ed4875a611f53041edb4909834#diff-d4900d5024081117910534bb6c472483R33
