### ISSUE TITLE
Some cli commands "hang"

### ISSUE THREAD

**Issue by radmen** [adonisjs/adonis-cli#60]
Looks like some of the command line scripts cause Node hangup.

eg: 

```bash
adonis route:list
```

Cli lists routes and "waits" indefinitely. I've tried to dig into this issue and it looks for me that some commands are returning Promise (function handlers are defined with `async` keyword) which is not resolved (or waits for resolving).

Some commands (eg `adonis --help`) stop node after execution.

I tried to write a fix for this however, I'm not sure whether the problem is in `adonis-cli` or simply in the commands that are executed. If it's the latter case it would require reviewing all packages providing commands for the framework.

**Comment by thetutlage** [comment]
None of the commands hangs for me, unless you are not connecting to Database in your startup code.

**Comment by radmen** [comment]
I've tried to reproduce the problem and... it's gone. Since I'm not able to reproduce it there's nothing to report. 

Sorry for problem.
