### ISSUE TITLE
skip loading `start/events.js` while running adonis/ace

### ISSUE THREAD

**Issue by radmen** [adonisjs/adonis-cli#64]
Can't say if I'm posting this issue on the right repo...

My application has defined some Redis event listeners in `event.js` file.
I've prepared a new command which is supposed to listen on MQ backend for new jobs (so it's a long-running command).

While running command application is still listening for events.  
In my case, it was resulting in doubled events which were later stored twice in db.

I know that this may not be an issue, however, I'm wondering whether this behavior is correct.  
Ace commands may have side-effects which should not happen while running a command.

IMO ace command should not listen for Redis events (in general not load `events.js` file).

What do you think about it?

**Comment by thetutlage** [comment]
The `events.js` is also used for other events via `Event` provider. So it's not possible to know whether to load or not load this file.

The best way is to create `start/redis.js` file and `preLoad` it on server start inside `server.js` file.

So it will be

```js
new Ignitor(require('@adonisjs/fold'))
  .preLoad('start/redis')
``` 

Docs here http://dev.adonisjs.com/docs/4.0/ignitor#_preloading_files

**Comment by radmen** [comment]
Ah, that makes sense. I thought that all files from `start` are loaded during bootup.

Thanks!
