### ISSUE TITLE
Use ncp?

### ISSUE THREAD

**Issue by benallfree** [adonisjs/adonis-cli#66]
Looking at `cli.copy` and wondering if [ncp](https://www.npmjs.com/package/ncp) would be helpful for package maintainers. If my package has multiple migration files, or multiple config files in subfolders, using `ncp` under the hood rather than `fs.copy` would make publishing easier. Thoughts?

**Comment by thetutlage** [comment]
Yes seems like it makes sense to use `ncp`. Adding to enhancements and will publish with final release, coming first week of November

**Comment by benallfree** [comment]
Please assign if you would like me to implement

**Comment by thetutlage** [comment]
Looking into it and found that there is catch with the package, that it will overwrite the existing files, I don't want that to happen

**Comment by benallfree** [comment]
Here is a sample that does not clobber https://github.com/benallfree/ncp-test

**Comment by RomainLanz** [comment]
@benallfree Could you create a PR with tests to verify that files aren't overwritten?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
