### ISSUE TITLE
'adonis install' should run npm post-install hook

### ISSUE THREAD

**Issue by benallfree** [adonisjs/adonis-cli#69]
I think(??) I found a bug that `adonis install` does not run the `postinstall` npm script.

I noticed this because I used `npm link` to local packages. Well, npm 5 has [a bug](https://github.com/npm/npm/issues/17287) where running `npm i` unlinks packages. So I have a post-install to put them back.

It works with `npm install` but not with `adonis install`.

**Comment by RomainLanz** [comment]
Hey @benallfree! 👋 

This is somehow weird since `adonis-cli` use `npm` directly to install the package.
https://github.com/adonisjs/adonis-cli/blob/develop/src/Commands/Install/steps/install.js#L29

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
