### ISSUE TITLE
Controller generator generating incorrect methods

### ISSUE THREAD

**Issue by watzon** [adonisjs/adonis-cli#70]
I don't know if it's the generator or the framework with the problem, but I'm putting this here. Currently the [controller generator](https://github.com/adonisjs/adonis-cli/blob/develop/src/Generators/templates/httpController.mustache#L23) creates a controller with the method `delete`, but when you call `Route.resource` it [generates a route](https://github.com/adonisjs/adonis-framework/blob/348f38fa3f7c72b49a148c726df39149f059b9bd/src/Route/Resource.js#L153) that is looking for a `destroy` method.

**Comment by RomainLanz** [comment]
Hey @watzon! 👋 

I believe with should change the generator even if it's the `Route.resource` that is wrong.
Changing the way `Route.resource` will result in a breaking change that we don't want.

May you create a PR to fi that?

**Comment by watzon** [comment]
@RomainLanz I was planning on it! Just wanted to make sure we were on the same page. I think the route should be `destroy` anyway.
