### ISSUE TITLE
'new' creates legacy version of adonis?

### ISSUE THREAD

**Issue by Xaz16** [adonisjs/adonis-cli#73]
Hi guys. 

I followed docs by this [url](http://adonisjs.com/docs/4.0/installation) and really confused when
`adonis new --only-api` 
didn't work but in docs it described. Ok, happens. But I can't understand this package.json 

```
...

"dependencies": {
    "adonis-ace": "^3.0.7",
    "adonis-auth": "^1.0.5",
    "adonis-commands": "^2.1.5",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.10",
    "adonis-lucid": "^3.0.14",
    "adonis-middleware": "^1.0.11",
    "adonis-websocket": "^1.0.3",
    "youch": "^2.0.4"
  },

...
```

As I understand v3.0 of adonis is deprecated(legacy) and as I see we have adonis packages for v4.0 but why cli creates deprecated project dependencies?
One more points is different hello world pages between docs and spawned by `adonis new` command.

**Comment by RomainLanz** [comment]
Hey @Xaz16! 👋 

Be sure to use the latest CLI which is `@adonisjs/cli` and not `adonis-cli`.

```bash
$ npm install -g @adonisjs/cli
```

> One more points is different hello world pages between docs and spawned by adonis new command.

Sorry, I didn't get your question.

**Comment by Xaz16** [comment]
> Be sure to use the latest CLI which is @adonisjs/cli and not adonis-cli.

![2017-11-12_23-44-45](https://user-images.githubusercontent.com/12300576/32703239-dcd0800e-c803-11e7-99cc-ae7ae59f3cf6.png)

Yes, I have latest version. 

> Sorry, I didn't get your question.

I mean difference between start screen from cli and docs 
![cli](https://user-images.githubusercontent.com/12300576/32703256-1232d0da-c804-11e7-965c-65603cd47118.png)
<img width="903" alt="welcome-page" src="https://user-images.githubusercontent.com/12300576/32703262-23977272-c804-11e7-80c0-5437de2b42b3.png">

**Comment by RomainLanz** [comment]
Ok, so the first landing page are the one from 3.2.

Could you please run `which adonis` and also try to first uninstall the 3.2 CLI then install the 4.0?

```
$ npm uninstall -g adonis-cli
$ npm install -g @adonisjs/cli
```

**Comment by Xaz16** [comment]
Thank you so much, but debugging through 'which' help me. It's strange thing that when I do
 ` npm install <anything>` 

it's installed in 
`/usr/local/bin and /Users/<your_user>/.nvm/versions/node/v8.9.1/bin/adonis`

Because later I installed adonis-cli my PATH see only 2.0 version which in /usr/local/bin and when I remove all adonis binaries from directories and made 
`npm install -g @adonisjs/cli`

it installed in nvm path and can't see adonis/cli v3.0, because it not specified in $PATH of my bash. When I use nvm path it works properly.

Look like trouble in my side. Sorry for disturbing. Thank you.

**Comment by RomainLanz** [comment]
I'm glad you get it solved!

Happy coding with Adonis 🚀
