### ISSUE TITLE
adonis make:controler <controller_name> silently fails

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/adonis-cli#79]
`adonis make:controller <controller_name>` where `<controller_name>` is any single word i.e. "Test" fails silently, it returns nothing and no files are created within app/Controllers/Http

It is my understanding that we should use `adonis make:controller <controller_name>` rather than `node ace make:controller <controller_name>` as the commands are proxied by the new CLI.

`node ace make:controller <controller name>` results in the following error:

`error: 'make:controller' is not a registered command`

**Comment by thetutlage** [comment]
The error from `node ace make:controller <controller name>` is valid, since this command exists on the `adonis-cli` package and is not part of your project.

Regarding `adonis make:controller`, can you share the OS you are on and also the Node.js version

**Comment by RaymondLC92** [comment]
@thetutlage Any update on this?

**Comment by thetutlage** [comment]
Nope! All seems to be working fine on my end and the weirdest part is, it is failing with no errors. Does other commands like `make:model` etc works fine?

**Comment by RaymondLC92** [comment]
The other commands also do not work, in fact it seems none of the commands work.

Are the commands installed by installing the CLI?

**Comment by RaymondLC92** [comment]
typing adonis with no command gives me the following:

adonis

  Usage:  [options] [command]


  Options:

    -h, --help  output usage information


  Commands:

    new [options] <name>  Scaffold a new AdonisJs application with the name provided.
  Extras:

    [command] --help output command detail info

**Comment by thetutlage** [comment]
Seems like you are running an old version of adonis cli. Install it as

```
npm i -g @adonisjs/cli
```

**Comment by RaymondLC92** [comment]
Odd, that's how our systemadmin says he installed it.

Regardless npm un -g @adonisjs/cli followed by an npm i -g @adonisjs/cli fixed it.

Thanks yet again.

**Comment by thetutlage** [comment]
👍
