### ISSUE TITLE
make:validator not found.

### ISSUE THREAD

**Issue by edDimensi** [adonisjs/adonis-cli#81]
Hi, in [docs](http://adonisjs.com/docs/4.0/validator#_route_validator) i see command `make:validator`. In cli i not found this command.
![screenshot_20171219_015414](https://user-images.githubusercontent.com/11390039/34132133-85aeb9b2-e45f-11e7-92ad-161277bcdf3f.png)

**Comment by thetutlage** [comment]
The command is added when you install and setup the vslidator provider 

```
adonis install @adonisjs/validator
```

**Comment by edDimensi** [comment]
Thx for answer.
