### ISSUE TITLE
i am having error installing adonis cli with npm

### ISSUE THREAD

**Issue by bachbil** [adonisjs/adonis-cli#83]
if i am doing this command 
npm i -g @adonisjs/cli
 i have this error

npm WARN optional Skipping failed optional dependency /@adonisjs/cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "@adonisjs/cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/faranda/npm-debug.log

please can someone help me?

**Comment by thetutlage** [comment]
The access to write inside `/usr/local/lib` has been denied to npm. Make sure npm can write to this directory or make use of `sudo`

**Comment by RomainLanz** [comment]
I recommend you to read https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by bachbil** [comment]
i've been fix the issue running the command with super user 
thanks
