### ISSUE TITLE
Not getting migration options in cli

### ISSUE THREAD

**Issue by rakshans1** [adonisjs/adonis-cli#84]
![image](https://user-images.githubusercontent.com/12949352/35182062-bd4e3f98-fdf3-11e7-8a8e-31a6c0d06065.png)

I am unable to run migration commands from cli v3.0.17 
error: `migration:run` is not a registered command

At first the migration commands where visibe 
![image](https://user-images.githubusercontent.com/12949352/35182097-4e8479fa-fdf4-11e7-9d78-ae190e83e28d.png)

I got error to install SQLite
![image](https://user-images.githubusercontent.com/12949352/35182144-09478af2-fdf5-11e7-8a81-25b63cb501c2.png)

After installing sqlite the migration command in not working.
I tried reinstalling the cli but no luck.

**Comment by ammezie** [comment]
Did you create the sqlite db file?

**Comment by thetutlage** [comment]
Can u share how you installed the cli? Which command did u ran to install it?

**Comment by thetutlage** [comment]
Okay and can you share the output of `adonis --help`. Make sure you are in the project root, since some commands are part of project. `migration:run` is available when you are inside the project root and have configured `@adonisjs/lucid` package.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by javisantos** [comment]
@thetutlage i know is closed but, same problem here with docker

Dockerfile:

FROM node:9.5.0-alpine

WORKDIR /www/app

ADD package.json /www/app
RUN npm install
RUN npm install -g @adonisjs/cli
RUN adonis --help
RUN adonis serve
ADD . /www/app


Log:

Step 6/9 : RUN npm install -g @adonisjs/cli
 ---> Running in 51d97d76652d
/usr/local/bin/adonis -> /usr/local/lib/node_modules/@adonisjs/cli/index.js

nodemon@1.14.12 postinstall /usr/local/lib/node_modules/@adonisjs/cli/node_modules/nodemon
node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')" || exit 0

Love nodemon? You can now support the project via the open collective:
https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@adonisjs/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

 @adonisjs/cli@4.0.0
added 302 packages in 21.599s
Removing intermediate container 51d97d76652d
 ---> 74aa4742b589
Step 7/9 : RUN adonis --help
 ---> Running in 994634d10356
Usage:
  command [arguments] [options]

Global Options:
  --env              Set NODE_ENV before running the commands
  --no-ansi          Disable colored output
  --version          output the version number

Available Commands:
  addon              Create a new AdonisJs addon
  install            Install Adonisjs provider from npm/yarn and run post install instructions
  new                Create a new AdonisJs application
  repl               Start a new repl session
  serve              Start Http server
 key
  key:generate       Generate secret key for the app
 make
  make:command       Make a new ace command
  make:controller    Make a new HTTP or Websocket channel controller
  make:ehandler      Make a new global exception handler
  make:exception     Make a new exception
  make:hook          Make a new lucid model hook
  make:listener      Make a new event or redis listener
  make:middleware    Make a new HTTP or Ws Middleware
  make:migration     Create a new migration file
  make:model         Make a new lucid model
  make:seed          Create a database seeder
  make:trait         Make a new lucid trait
  make:view          Make a view file
 route
  route:list         List all registered routes
 run
  run:instructions   Run instructions for a given module
Removing intermediate container 994634d10356
 ---> b3d90960258e
Step 8/9 : RUN adonis serve
 ---> Running in 5c00bd89726b
Make sure you are inside an adonisjs app to start the server
Removing intermediate container 5c00bd89726b
 ---> 7f906a8c1d82
Step 9/9 : ADD . /www/app
 ---> d779aea9080e
Successfully built d779aea9080e

**Comment by javisantos** [comment]
Fixed

FROM node:9.5.0-alpine
LABEL Javi Santos

WORKDIR /www/app

ADD package.json /www/app
RUN npm install
RUN npm install -g @adonisjs/cli
ADD . /www/app
RUN adonis migration:run
RUN adonis serve

I gues is checking for something in the congif files before showing the "migration" options
