### ISSUE TITLE
Resourceful Controllers using delete method instead of destroy

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-cli#86]
_From @bolt12 on January 21, 2018 19:1_

I just noticed that if i create a new Controller using

`adonis make:controller <name> --resource`

it will create a new file with all route resources but the last one is called delete, and looking into the docs it should be destroy.

_Copied from original issue: adonisjs/adonis-api-app#14_

**Comment by ammezie** [comment]
@thetutlage already working on this?

**Comment by RomainLanz** [comment]
This is already fixed.

A PR was sent by @watzon on the 7 November https://github.com/adonisjs/adonis-cli/commit/86e00216b2968dbb83720083bb938bf63e83f392

**Comment by ammezie** [comment]
Awesome!!!
