### ISSUE TITLE
Error: Cannot find module ../../../ib/boxen

### ISSUE THREAD

**Issue by tomerof** [adonisjs/adonis-cli#93]
Hi, i just install adois's cli on a new mac,
when I'm running the serve command I'm getting this error:
Error: Cannot find module '../../../lib/boxen'
but the server works.

**Comment by RomainLanz** [comment]
Hey @tomerof! 👋 

Could you try to reinstall `@adonisjs/cli` and try again?

**Comment by RomainLanz** [comment]
and which version of nodejs are you using?

**Comment by thetutlage** [comment]
Not sure how I shipped this weird bug. Somehow the error got swallowed on Mac. Anyways I have released a new version, please update the cli.

```
npm i -g @adonisjs/cli@latest
```
