### ISSUE TITLE
adonis new yardstick --api-only not work

### ISSUE THREAD

**Issue by vrwebdesign** [adonisjs/adonis-cli#97]
when i use this command in terminal  this error occurred

> error: unknown option `--api-only'

**Comment by thetutlage** [comment]
Can you share the complete command and how did you installed the CLI?

**Comment by vrwebdesign** [comment]
`adonis new test --api-only`

>   error: unknown option `--api-only'

**Comment by thetutlage** [comment]
You are using a way older cli

Install it as 

```
npm i -g @adonisjs/cli
```

**Comment by vrwebdesign** [comment]
tnx
